# @Sdc.LoggingService_HostAddress = http://localhost:32786
@Sdc.LoggingService_HostAddress = http://localhost:8080


GET {{Sdc.LoggingService_HostAddress}}/logs?limit=100
Accept: application/json

###

GET {{Sdc.LoggingService_HostAddress}}/openapi/v1.json
Accept: application/json

###
