services:
  logger:
    build:
      context: .
      dockerfile: LoggerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    ports:
      - "8000:8000"
    networks:
      - sportsref-net
    volumes:
      - ../data/logger-service/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  sportsref-net:
    driver: bridge
