services:
  logging-service:
    build:
      context: .
      dockerfile: Sdc.LoggingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - sdc-net
    volumes:
      - ./container-data/logging-service/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/weatherforecast"]
      interval: 30s
      timeout: 1s
      retries: 3

networks:
  sdc-net:
    driver: bridge
